#!/usr/bin/env bash
 set -e
# The ssh keys were generated by
# ssh-keygen -f keys/id_rsa -t rsa -b 4096 -C "ubuntu@my-domain.com" -N ""

echo 'Getting public ssh key'
cat ~/.ssh/id_rsa.pub > packer/authorized_keys

function exportVariables() {
    export DRY_RUN=${1}
    echo 'INFO:export aws credential variables'
    for env in $(cat aws-credentials.properties); do
        export $env
    done
}

function packerExecution() {
    packer validate 'packer/template.json'
    if [ ${DRY_RUN} == 'false' ]; then
        packer build -force -color=false 'packer/template.json'
        AMI_ID=$(aws ec2 describe-images --region ${AWS_DEFAULT_REGION}  --filters "Name=tag-key,Values=Name,Name=tag-value,Values=Infosan-Base-Image" --query 'Images[*].{id:ImageId}' | jq .[].id | cut -f2 -d'"')
cat << EOF >>  'aws-credentials.properties'
AWS_AMI_ID=${AMI_ID}
EOF
    echo "The new image id: ${AMI_ID}"
    fi
}

exportVariables ${1}
python replace_packer.py
packerExecution ${1}