---
driver:
  name: vagrant

driver_config:
  requre_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  synced_folders:
    - ['../assets', '/tmp/assets']

provisioner:
  product_name: chef
  product_version: 12.20.3

platforms:
  - name: ubuntu-16.04

suites:
  - name: app-server
    driver:
      log_level: debug
      network:
        - ['public_network', {ip: '192.168.1.110', bridge: 'en0: Wi-Fi (AirPort)'}]
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::nginx]
    attributes: {
       set_fqdn: 'app-server'
    }

  - name: data-base-master
    driver:
      log_level: debug
      network:
        - ['public_network', {ip: '192.168.1.111', bridge: 'en0: Wi-Fi (AirPort)'}]
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::postgresql]
    attributes: {
      set_fqdn: 'data-base-master',
      postgresql: {
        replication: true,
        is_master: true,
        master_address: '192.168.1.111',
        slave_address: '192.168.1.112'
      }
    }

  - name: data-base-slave
    driver:
      log_level: debug
      network:
        - ['public_network', {ip: '192.168.1.112', bridge: 'en0: Wi-Fi (AirPort)'}]
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::postgresql]
    attributes: {
      set_fqdn: 'data-base-slave',
      postgresql: {
      replication: true,
        is_slave: true,
        master_address: '192.168.1.111',
        slave_address: '192.168.1.112'
       }
    }