---
driver:
  name: vagrant

driver_config:
  requre_chef_omnibus: true
  network:
  - ['forwarded_port', { guest: 8080, host: 8080 }]

  customize:
    cpus: 1
    memory: 512
  synced_folders:
    - ['../assets', '/tmp/assets']

provisioner:
  product_name: chef
  product_version: 12.20.3

platforms:
  - name: ubuntu-16.04

suites:
  - name: app-server
    driver:
      log_level: debug
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::nginx]
    attributes: {
       set_fqdn: 'app-server'
    }

  - name: data-base-master
    driver:
      log_level: debug
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::postresql]
    attributes: {
       set_fqdn: 'data-base-master',
       postgresql: {
        replication: true
      }
    }

  - name: data-base-slave
    driver:
      log_level: debug
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::postresql]
    attributes: {
       set_fqdn: 'data-base-slave'
    }