---
driver:
  name: vagrant

driver_config:
  requre_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  synced_folders:
    - ['../assets', '/tmp/assets']

provisioner:
  product_name: chef
  product_version: 12.20.3

platforms:
  - name: ubuntu-16.04

suites:
  - name: app-server
    driver:
      log_level: debug
      network:
        - ['private_network', {ip: '10.0.2.10'}]
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::nginx]
    attributes: {
       set_fqdn: 'app-server'
    }

  - name: data-base-master
    driver:
      log_level: debug
      network:
        - ['private_network', {ip: '10.0.2.11'}]
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::postgresql]
    attributes: {
      set_fqdn: 'data-base-master',
      postgresql: {
        replication: true,
        is_master_address: true,
        master_address: '10.0.2.11',
        slave_address: '10.0.2.12'
      }
    }

  - name: data-base-slave
    driver:
      log_level: debug
      network:
        - ['private_network', {ip: '10.0.2.12'}]
    run_list:
      - recipe[fully-chef::default]
      - recipe[fully-chef::postgresql]
    attributes: {
      set_fqdn: 'data-base-slave',
      postgresql: {
      replication: true,
        is_slave_address: true,
        master_address: '10.0.2.11',
        slave_address: '10.0.2.12'
       }
    }